/*2
*/

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package isign;

/**
 *
 * @author Mavis
 */
public class iSign extends javax.swing.JFrame {

    /**
     * Creates new form iSign
     */
    public iSign() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        root = new javax.swing.JPanel();
        home_p = new javax.swing.JPanel();
        welcome_l = new javax.swing.JLabel();
        s1_go_b = new javax.swing.JButton();
        s2_go_b = new javax.swing.JButton();
        s3_go_b = new javax.swing.JButton();
        s1_info_l = new javax.swing.JLabel();
        s2_info_l = new javax.swing.JLabel();
        s3_info_l = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        s1_panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        sym1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        background1 = new javax.swing.JLabel();
        s2_panel = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        background2 = new javax.swing.JLabel();
        s3_panel = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        background3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("iSign");
        setPreferredSize(new java.awt.Dimension(1024, 700));
        setResizable(false);

        root.setLayout(new java.awt.CardLayout());

        home_p.setBackground(new java.awt.Color(102, 102, 102));
        home_p.setPreferredSize(new java.awt.Dimension(1024, 700));
        home_p.setLayout(null);

        welcome_l.setFont(new java.awt.Font("Lucida Handwriting", 0, 48)); // NOI18N
        welcome_l.setForeground(new java.awt.Color(255, 255, 255));
        welcome_l.setText("Welcome to iSign!");
        home_p.add(welcome_l);
        welcome_l.setBounds(260, 30, 500, 90);

        s1_go_b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/ereader.png"))); // NOI18N
        s1_go_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1_go_bActionPerformed(evt);
            }
        });
        home_p.add(s1_go_b);
        s1_go_b.setBounds(60, 190, 280, 310);

        s2_go_b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/learning.png"))); // NOI18N
        s2_go_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s2_go_bActionPerformed(evt);
            }
        });
        home_p.add(s2_go_b);
        s2_go_b.setBounds(370, 190, 280, 310);

        s3_go_b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/chat.png"))); // NOI18N
        s3_go_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s3_go_bActionPerformed(evt);
            }
        });
        home_p.add(s3_go_b);
        s3_go_b.setBounds(680, 190, 280, 310);

        s1_info_l.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        s1_info_l.setForeground(new java.awt.Color(255, 255, 255));
        s1_info_l.setText("Step 1: Learn Symbols");
        home_p.add(s1_info_l);
        s1_info_l.setBounds(100, 510, 210, 40);

        s2_info_l.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        s2_info_l.setForeground(new java.awt.Color(255, 255, 255));
        s2_info_l.setText("Step 2: Review Contents");
        home_p.add(s2_info_l);
        s2_info_l.setBounds(400, 510, 230, 40);

        s3_info_l.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        s3_info_l.setForeground(new java.awt.Color(255, 255, 255));
        s3_info_l.setText("Step 3: Generate Sentences");
        home_p.add(s3_info_l);
        s3_info_l.setBounds(690, 510, 260, 40);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/background.png"))); // NOI18N
        background.setPreferredSize(new java.awt.Dimension(1024, 700));
        background.setRequestFocusEnabled(false);
        home_p.add(background);
        background.setBounds(0, 0, 3000, 1800);

        root.add(home_p, "card2");

        s1_panel.setBackground(new java.awt.Color(102, 102, 102));
        s1_panel.setPreferredSize(new java.awt.Dimension(1024, 700));
        s1_panel.setLayout(null);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Please choose a symbol to learn", 0, 0, new java.awt.Font("Malayalam MN", 0, 14), new java.awt.Color(255, 204, 51))); // NOI18N
        jScrollPane1.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, background1, org.jdesktop.beansbinding.ELProperty.create("${background}"), jScrollPane1, org.jdesktop.beansbinding.BeanProperty.create("background"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, background1, org.jdesktop.beansbinding.ELProperty.create("${background}"), jScrollPane1, org.jdesktop.beansbinding.BeanProperty.create("foreground"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, background1, org.jdesktop.beansbinding.ELProperty.create("${background}"), jPanel3, org.jdesktop.beansbinding.BeanProperty.create("background"));
        bindingGroup.addBinding(binding);

        jPanel3.setLayout(null);

        sym1.setText("symbol1");
        sym1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sym1ActionPerformed(evt);
            }
        });
        jPanel3.add(sym1);
        sym1.setBounds(10, 10, 80, 70);

        jScrollPane1.setViewportView(jPanel3);

        s1_panel.add(jScrollPane1);
        jScrollPane1.setBounds(40, 50, 940, 220);

        jLabel1.setFont(new java.awt.Font("Malayalam MN", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("jLabel1");
        s1_panel.add(jLabel1);
        jLabel1.setBounds(470, 320, 110, 50);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        s1_panel.add(jPanel1);
        jPanel1.setBounds(40, 290, 340, 310);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        s1_panel.add(jPanel2);
        jPanel2.setBounds(640, 290, 340, 310);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        s1_panel.add(jButton1);
        jButton1.setBounds(40, 630, 75, 29);

        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/background.png"))); // NOI18N
        background1.setPreferredSize(new java.awt.Dimension(1024, 700));
        background1.setRequestFocusEnabled(false);
        s1_panel.add(background1);
        background1.setBounds(0, 0, 3000, 1800);

        root.add(s1_panel, "card3");

        s2_panel.setLayout(null);

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        s2_panel.add(jButton2);
        jButton2.setBounds(50, 550, 97, 29);

        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/background.png"))); // NOI18N
        background2.setPreferredSize(new java.awt.Dimension(1024, 700));
        background2.setRequestFocusEnabled(false);
        s2_panel.add(background2);
        background2.setBounds(0, 0, 3000, 1800);

        root.add(s2_panel, "card4");

        s3_panel.setLayout(null);

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        s3_panel.add(jButton3);
        jButton3.setBounds(40, 560, 97, 29);

        background3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/background.png"))); // NOI18N
        background3.setPreferredSize(new java.awt.Dimension(1024, 700));
        background3.setRequestFocusEnabled(false);
        s3_panel.add(background3);
        background3.setBounds(0, 0, 3000, 1800);

        root.add(s3_panel, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(root, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(root, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void s1_go_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1_go_bActionPerformed

        java.awt.CardLayout cl = (java.awt.CardLayout)(root.getLayout());
        cl.show(root,"card3");
        // TODO add your handling code here:
    }//GEN-LAST:event_s1_go_bActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout)(root.getLayout());
        cl.first(root);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void s2_go_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s2_go_bActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout)(root.getLayout());
        cl.show(root,"card4");// TODO add your handling code here:
    }//GEN-LAST:event_s2_go_bActionPerformed

    private void s3_go_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s3_go_bActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout)(root.getLayout());
        cl.show(root,"card5");// TODO add your handling code here:
    }//GEN-LAST:event_s3_go_bActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout)(root.getLayout());
        cl.first(root);// TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout)(root.getLayout());
        cl.first(root);// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void sym1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sym1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sym1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(iSign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(iSign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(iSign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(iSign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new iSign().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel background1;
    private javax.swing.JLabel background2;
    private javax.swing.JLabel background3;
    private javax.swing.JPanel home_p;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel root;
    private javax.swing.JButton s1_go_b;
    private javax.swing.JLabel s1_info_l;
    private javax.swing.JPanel s1_panel;
    private javax.swing.JButton s2_go_b;
    private javax.swing.JLabel s2_info_l;
    private javax.swing.JPanel s2_panel;
    private javax.swing.JButton s3_go_b;
    private javax.swing.JLabel s3_info_l;
    private javax.swing.JPanel s3_panel;
    private javax.swing.JButton sym1;
    private javax.swing.JLabel welcome_l;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
